/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesosDatos.ColectivoData;
import Entidades.Colectivo;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class ColectivoVistas extends javax.swing.JInternalFrame {

    Colectivo cole = null;

    /**
     * Creates new form ColectivoVistas
     */
    public ColectivoVistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTFmarca = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFmatricula = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        JTFmodelo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        JTFcapacidad = new javax.swing.JTextField();
        JCBestado = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        JBguardar = new javax.swing.JButton();
        JBnuevo = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gestion de Colectivo");

        jLabel2.setText("Marca");

        JTFmarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFmarcaActionPerformed(evt);
            }
        });

        jLabel3.setText("Matricula");

        JTFmatricula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFmatriculaActionPerformed(evt);
            }
        });

        jLabel4.setText("Modelo");

        JTFmodelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFmodeloActionPerformed(evt);
            }
        });

        jLabel5.setText("Capacidad");

        JTFcapacidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFcapacidadActionPerformed(evt);
            }
        });

        jLabel6.setText("Estado");

        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        JBnuevo.setText("Nuevo");
        JBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActionPerformed(evt);
            }
        });

        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTFmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JTFcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JCBestado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JTFmarca, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JTFmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JBguardar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(JBsalir)
                        .addComponent(JBnuevo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTFmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBguardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFmatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBnuevo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(JTFcapacidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(JCBestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(JBsalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFmarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFmarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFmarcaActionPerformed

    private void JTFmatriculaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFmatriculaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFmatriculaActionPerformed

    private void JTFmodeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFmodeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFmodeloActionPerformed

    private void JTFcapacidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFcapacidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFcapacidadActionPerformed

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
        dispose();
    }//GEN-LAST:event_JBsalirActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
        
        ColectivoData cd = new ColectivoData();
        
        try {
            
            String marca = JTFmarca.getText();
            String matricula = JTFmatricula.getText();
            String modelo = JTFmodelo.getText();
            int capacidad = Integer.parseInt(JTFcapacidad.getText());
            
            if (marca.isEmpty()) {
                JOptionPane.showMessageDialog(null, "La marca no puede estar vacia");
                JTFmarca.requestFocus();
            }
            if (matricula.isEmpty()) {
                JOptionPane.showMessageDialog(null, "La matricula no puede estar vacia");
                JTFmatricula.requestFocus();
            }
            if(modelo.isEmpty()){
            JOptionPane.showMessageDialog(null, "El modelo no puede estar vacio");
            JTFmodelo.requestFocus();
            }
         
            boolean estado = JCBestado.isSelected();
            
            if(cole==null){
            cole = new Colectivo(matricula, marca, modelo, capacidad, estado);
            cd.añadirColectivo(cole);
            }
           
            

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "La capacidad debe ser un numero");
            JTFcapacidad.setText("");
            JTFcapacidad.requestFocus();
        }

    }//GEN-LAST:event_JBguardarActionPerformed

    private void JBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_JBnuevoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBnuevo;
    private javax.swing.JButton JBsalir;
    private javax.swing.JCheckBox JCBestado;
    private javax.swing.JTextField JTFcapacidad;
    private javax.swing.JTextField JTFmarca;
    private javax.swing.JTextField JTFmatricula;
    private javax.swing.JTextField JTFmodelo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
private void limpiar(){
    JTFcapacidad.setText("");
    JTFmarca.setText("");
    JTFmatricula.setText("");
    JCBestado.setSelected(false);
    cole=null;
    }


}


