/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesosDatos.*;
import Entidades.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class PasajeroVistas extends javax.swing.JInternalFrame {
Pasajero pas=new Pasajero();

    /**
     * Creates new form PasajeroVistas
     */
    public PasajeroVistas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNombre = new javax.swing.JLabel();
        jLabelEstado = new javax.swing.JLabel();
        jCestado = new javax.swing.JCheckBox();
        JTFdocumento = new javax.swing.JTextField();
        JTFapellido = new javax.swing.JTextField();
        JTFnombre = new javax.swing.JTextField();
        jButtonNuevo = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelDocumento = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabelApellido = new javax.swing.JLabel();
        Titulo = new javax.swing.JLabel();
        JTFemail = new javax.swing.JTextField();
        jLabelNombre1 = new javax.swing.JLabel();
        JTFtelefono = new javax.swing.JTextField();
        jLabelNombre2 = new javax.swing.JLabel();

        jLabelNombre.setText("Nombre");

        jLabelEstado.setText("Estado");

        JTFdocumento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFdocumentoActionPerformed(evt);
            }
        });

        JTFnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFnombreActionPerformed(evt);
            }
        });

        jButtonNuevo.setText("Nuevo");
        jButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNuevoActionPerformed(evt);
            }
        });

        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });

        jLabelDocumento.setText("Documento");

        jButtonGuardar.setText("Guardar");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabelApellido.setText("Apellido");

        Titulo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        Titulo.setText("Pasajero");

        JTFemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFemailActionPerformed(evt);
            }
        });

        jLabelNombre1.setText("E-mail");

        JTFtelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFtelefonoActionPerformed(evt);
            }
        });

        jLabelNombre2.setText("Telefono");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(32, 32, 32)
                                    .addComponent(jCestado))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabelApellido)
                                        .addComponent(jLabelDocumento)
                                        .addComponent(jLabelNombre1))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(JTFapellido, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                        .addComponent(JTFdocumento, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
                                        .addComponent(JTFemail, javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(JTFnombre, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabelNombre2)
                                    .addGap(18, 18, 18)
                                    .addComponent(JTFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelNombre))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonNuevo)
                        .addGap(70, 70, 70)
                        .addComponent(jButtonGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonSalir)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(141, 141, 141)
                .addComponent(Titulo)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Titulo)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTFdocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelDocumento))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelApellido)
                    .addComponent(JTFapellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre)
                    .addComponent(JTFnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre1)
                    .addComponent(JTFemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNombre2)
                    .addComponent(JTFtelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEstado)
                    .addComponent(jCestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNuevo)
                    .addComponent(jButtonSalir)
                    .addComponent(jButtonGuardar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTFdocumentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFdocumentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFdocumentoActionPerformed

    private void JTFnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFnombreActionPerformed

    private void jButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_jButtonNuevoActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
     PasajerosData pd=new PasajerosData();
        try {
            int DNI=Integer.parseInt(JTFdocumento.getText());
            String dni=JTFdocumento.getText();
            String nombre=JTFnombre.getText();
            String apellido=JTFapellido.getText();
            String email=JTFemail.getText();
            String tel=JTFtelefono.getText();
            if (nombre.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El nombre no puede estar vacio");
                JTFnombre.requestFocus();
            }
            if (apellido.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El apellido no puede estar vacio");
                JTFapellido.requestFocus();
            }
            if (email.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El email no puede estar vacio");
                JTFemail.requestFocus();
            }
            if (tel.isEmpty()) {
                JOptionPane.showMessageDialog(null, "El telefono no puede estar vacio");
                JTFtelefono.requestFocus();
            }
              
            boolean estado =jCestado.isSelected();
            
            if(pas==null){
             pas=new Pasajero(nombre,apellido,dni,email,tel,estado);
             pd.añadirPasajero(pas);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El dni debe ser un numero");
            JTFdocumento.setText("");
            JTFdocumento.requestFocus();
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void JTFemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFemailActionPerformed

    private void JTFtelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFtelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFtelefonoActionPerformed

    private void limpiar(){
    JTFnombre.setText("");
    JTFapellido.setText("");
    JTFdocumento.setText("");
    JTFemail.setText("");
    JTFtelefono.setText("");
    jCestado.setSelected(false);
    pas=null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTFapellido;
    private javax.swing.JTextField JTFdocumento;
    private javax.swing.JTextField JTFemail;
    private javax.swing.JTextField JTFnombre;
    private javax.swing.JTextField JTFtelefono;
    private javax.swing.JLabel Titulo;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonNuevo;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JCheckBox jCestado;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelDocumento;
    private javax.swing.JLabel jLabelEstado;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNombre1;
    private javax.swing.JLabel jLabelNombre2;
    // End of variables declaration//GEN-END:variables
}
