/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import AccesosDatos.RutaData;
import Entidades.Ruta;
import java.sql.Time;
import java.time.LocalTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;

/**
 *
 * @author Lucas
 */
public class RutaVistas extends javax.swing.JInternalFrame {
    Ruta ruta = null;
  
    /**
     * Creates new form RutaVistas
     */
    public RutaVistas() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JTForigen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        JTFdestino = new javax.swing.JTextField();
        JTFduracion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        JCBestado = new javax.swing.JCheckBox();
        JBguardar = new javax.swing.JButton();
        JBnuevo = new javax.swing.JButton();
        JBsalir = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Gestion de Ruta");

        jLabel2.setText("Origen");

        JTForigen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTForigenActionPerformed(evt);
            }
        });

        jLabel3.setText("Destino");

        JTFdestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFdestinoActionPerformed(evt);
            }
        });

        JTFduracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTFduracionActionPerformed(evt);
            }
        });

        jLabel4.setText("Duracion Estimada");

        jLabel6.setText("Estado");

        JBguardar.setText("Guardar");
        JBguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBguardarActionPerformed(evt);
            }
        });

        JBnuevo.setText("Nuevo");
        JBnuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBnuevoActionPerformed(evt);
            }
        });

        JBsalir.setText("Salir");
        JBsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(JTFdestino, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JTForigen, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(98, 98, 98)
                            .addComponent(jLabel1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(65, 65, 65)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(JCBestado)
                                .addComponent(JTFduracion)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JBguardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JBnuevo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBsalir)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JTForigen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JTFdestino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBguardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JTFduracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JBnuevo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(JCBestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(JBsalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JTForigenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTForigenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTForigenActionPerformed

    private void JTFdestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFdestinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFdestinoActionPerformed

    private void JTFduracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTFduracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JTFduracionActionPerformed

    private void JBguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBguardarActionPerformed
      RutaData rutaData = new RutaData();
        try {
          String origen = JTForigen.getText();
          String destino = JTFdestino.getText();
          LocalTime duracion =LocalTime.parse(JTFduracion.getText(), DateTimeFormatter.ofPattern("HH:mm:ss"));
  
          if(origen.isEmpty()){
            JOptionPane.showMessageDialog(null,"El Origen no puede estar vacio");
            JTForigen.requestFocus();
            return;
          }
          if(destino.isEmpty()){
          JOptionPane.showMessageDialog(null, "El destino no puede estar vacio");
          JTFdestino.requestFocus();
          return;
          }
          if(duracion==null){
          JOptionPane.showMessageDialog(null, "La duracion no puede estar vacia");
          JTFduracion.requestFocus();
          return;
          }
          
          try {
            duracion = LocalTime.parse(JTFduracion.getText(), DateTimeFormatter.ofPattern("HH:mm:ss"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un formato de hora correcto (HH:mm:ss)");
            JTFduracion.setText("");
            JTFduracion.requestFocus();
            return;
        }

          boolean estado = JCBestado.isSelected();
          
          if(ruta==null){
          ruta = new Ruta(origen, destino, duracion, estado);
          rutaData.agregarRuta(ruta);
          }
          } 
        
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ingrese un formato de hora correcto");
            JTFduracion.setText("");
            JTFduracion.requestFocus();
        }
             
    }//GEN-LAST:event_JBguardarActionPerformed

    private void JBnuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBnuevoActionPerformed
        limpiar();
    }//GEN-LAST:event_JBnuevoActionPerformed

    private void JBsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsalirActionPerformed
    dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_JBsalirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBguardar;
    private javax.swing.JButton JBnuevo;
    private javax.swing.JButton JBsalir;
    private javax.swing.JCheckBox JCBestado;
    private javax.swing.JTextField JTFdestino;
    private javax.swing.JTextField JTFduracion;
    private javax.swing.JTextField JTForigen;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
    private void limpiar(){
    JTForigen.setText("");
    JTFdestino.setText("");
    JTFduracion.setText("");
    JCBestado.setSelected(false);
    ruta=null;
    }


}



